### ISSUE TITLE
Warning: Received `false` for a non-boolean attribute `className`. 

### ISSUE THREAD

**Issue by mcdave029** [rmosolgo/graphiql-rails#60] opened 2018-11-23 06:27 UTC
Rails: 2.5.1
Ruby: 2.5.3
![screen shot 2018-11-23 at 2 23 50 pm](https://user-images.githubusercontent.com/4713628/48930487-bee34e00-ef2b-11e8-8680-f2f5375c4902.png)
I dont know why am receiving this kind of error because it was said fix in latest graphiql update
https://github.com/graphql/graphiql/commit/7764ba59df45b8acd8b08c6ebce12f7049fa0197.

**Comment by dorianco** [comment] 2018-11-23 08:17
Same error here with rails-api setup

Gemfile

```ruby
    graphiql-rails (1.5.0)
    graphql (1.8.11)
    graphql-docs (1.6.0)
      commonmarker (~> 0.16)
      escape_utils (~> 1.2)
      extended-markdown-filter (~> 0.4)
      gemoji (~> 3.0)
      graphql (~> 1.6)
      html-pipeline (~> 2.8)
      sass (~> 3.4)
    graphql-errors (0.2.0)
      graphql (>= 1.6.0, < 2)
    graphql-guard (1.2.1)
      graphql (>= 1.6.0, < 2)
```

**Comment by shelmire** [comment] 2019-01-19 21:06
Caused by an error that was recently fixed in graphiql: https://github.com/graphql/graphiql/pull/724

Looks like there hasn't been a release since it was merged though.

**Comment by heatherbooker** [comment] 2019-06-27 20:26
I had this error and updated to `0.13.2` and error is gone! 🙌

**Comment by rmosolgo** [comment] 2024-02-23 18:50
I think this was fixed upstream -- thanks for sharing your findings here :+1:

**Closed by rmosolgo** 2024-02-23 18:50 UTC
